In [1]:
import numpy as np

In [12]:
np.random.choice(10), np.random.randint(0,10)

(7, 6)

In [13]:
np.random.choice(10, 5), np.random.randint(0,10, 5)

(array([1, 5, 4, 3, 0]), array([6, 0, 9, 3, 4]))

In [14]:
np.random.choice(a = 10, size = 5)

array([5, 2, 8, 3, 1])

In [15]:
np.random.randint(low=0,high=10, size=5)

array([5, 6, 4, 5, 8])

In [16]:
p = [0.1, 0, 0.3, 0.6, 0]

In [17]:
np.random.choice(a=10, size =5, p=p)

ValueError: ignored

In [18]:
np.random.choice(a=5, size =5, p=p)

array([3, 3, 3, 2, 3])