In [32]:
import numpy as np
import torch
import tensorflow as tf

In [57]:
# [0, 1) 범위 내에서 균일하게 분포된 난수를 생성
print("numpy", np.random.rand(5))
print("torch", torch.rand(5))
print("tensorflow", tf.random.uniform(shape=(5,)))

numpy [0.58898821 0.9090524  0.55963631 0.3208566  0.13787079]
torch tensor([0.8369, 0.3747, 0.6526, 0.4255, 0.9629])
tensorflow tf.Tensor([0.9677826  0.84752536 0.26275766 0.6527345  0.64443314], shape=(5,), dtype=float32)


In [58]:
# (범위가 [0, 4]) 중 임의로 선택한 숫자들을 포함하는 길이가 5
print(np.random.randint(5, size=(5,)))
print("torch", torch.randint(5, size=(5,)))

uniform_float = tf.random.uniform(shape=(5,), minval=0, maxval=5, dtype=tf.float32)
print("tensorflow", tf.dtypes.cast(uniform_float, dtype=tf.int32))

[2 3 4 0 3]
torch tensor([4, 0, 0, 4, 2])
tensorflow tf.Tensor([1 3 0 1 1], shape=(5,), dtype=int32)


In [59]:
# 표준 정규 분포(평균 0, 표준 편차 1)에서 난수를 생성
print("numpy", np.random.randn(5))
print("torch", torch.randn(5))
print("tensorflow", tf.random.normal(shape=(5,)))

numpy [-2.61208473  0.24647735 -0.53172702  1.07093896  1.20383833]
torch tensor([0.6675, 0.2782, 0.9835, 2.8401, 0.9286])
tensorflow tf.Tensor([ 1.2271191   0.18503666 -1.2535399   0.6432251  -1.2461982 ], shape=(5,), dtype=float32)


---

In [45]:
torch.empty(size=(3,3))

tensor([[ 2.1188e-13,  4.3565e-41, -6.8961e+25],
        [ 3.2434e-41,  5.6350e-15,  4.3565e-41],
        [-5.6670e+13,  4.3562e-41,  3.2851e-10]])